import tkinter as tk
from tkinter import filedialog

# File dialog function generated by tkinter
# The choosing image element from streamlit takes the image as in-memory object
# It is necessary to run it into a different thread to have the path
# The path is necessary to create the dataloader later
def select_file():
    root = tk.Tk()
    root.withdraw()
    file_path = filedialog.askopenfilename(
        title="Select an Image",
        filetypes=[("Image files", "*.jpg *.jpeg *.png *.bmp *.gif")]
    )
    print(f"{file_path}")

    return file_path

if __name__ == "__main__":
    file_path = select_file()